version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0

    steps:
      - checkout

      - run:
          name: Add Node.js PPA
          command: 'curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -'

      - run:
          name: Install Node.js
          command:  'sudo apt-get install nodejs'

      - run:
          name: Install, Configure & Start Postgres
          command: sudo apt-get install wget ca-certificates ; wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - ; sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' ; sudo apt-get install postgresql postgresql-contrib ; sudo update-rc.d postgresql enable ; sudo service postgresql start

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Check our user
          command:  'whoami'

      - run:
          name: Create CircleCI role
          command:  sudo su - postgres ; createuser -sd circleci ; exit

      - run:
          name: Create Database
          command: rails db:create

      - run:
          name: Setup Database
          command: rails db:schema:load --trace

      - run:
          name: database migration
          command: bundle exec rake db:migrate

      - run:
          name: Run tests
          command: bundle exec rspec

      - run:
          name: run Rubocop
          command: bundle exec rubocop
