version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0

    steps:
      - run:
          name: Get visability
          command: |
              echo 'Docker build passed'

      - run:
          name: Check ruby version
          command: 'ruby -v'

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Get visability
          command: |
              echo 'Bundle install passed'

      - run:
          name: Setup database
          command: /bin/rails db:schema:load --trace

      - run:
          name: Get visability
          command: |
             echo 'DB setup passed'


      - run:
          name: database migration
          command: bundle exec rake db:migrate

      - run:
          name: Get visability
          command: |
              echo 'DB Migration passed'

      - run:
          name: Run tests
          command: bundle exec rspec

      - run:
          name: run Rubocop
          command: bundle exec rubocop
