version: 2
jobs:
  build:
    working_directory: ~/acebook-derailed-team

    docker:
      image: circleci/ruby:2.5.0
      environment:
        BUNDLER_VERSION: 1.17.3

    steps:
      - run:
        name: bundle install
        command: |
          bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Setup database
          command: bin/rails db:schema:load --trace

      - run:
          name: database migration
          command: bundle exec rake db:migrate

      - run:
          name: Run tests
          command: bundle exec rspec

      - run:
          name: run Rubocop
          command: bundle exec rubocop
